# A string used to distinguish different Supabase projects on the same host.
project_id = "testagram"

[api]
port = 54321
schemas = ["public", "content", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 17

[studio]
port = 54323

openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
port = 54324

[storage]
file_size_limit = "50MiB"

[storage.buckets.fonts]
public = true
objects_path = "buckets/fonts"

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = [
    "https://*-supabase.vercel.app/*/*",
    "http://localhost:3000/*/*",
]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.external.apple]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[functions.search-embeddings]
verify_jwt = false

[functions.register-push-token]
verify_jwt = true

[functions.notification-delivery-worker]
verify_jwt = false

[functions.storage-node-gateway]
verify_jwt = false
